### ISSUE TITLE
How to save the model and predict another data?

### ISSUE THREAD

**Issue by iamsile** [matpalm/snli_nn#1]
Hi, matpalm!
When I use baseline.py to train a model, How to save it? Is it save the layers?
When I save the layers and load it again to predict another data, It always say:

Traceback (most recent call last):
  File "/Users/xxx/PycharmProjects/SNLI/predict.py", line 205, in <module>
    updates=updates)
  File "/Library/Python/2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/Library/Python/2.7/site-packages/theano/compile/pfunc.py", line 526, in pfunc
    output_keys=output_keys)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 1777, in orig_function
    output_keys=output_keys).create(
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 1416, in **init**
    self._check_unused_inputs(inputs, outputs, on_unused_input)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 1554, in _check_unused_inputs
    i.variable, err_msg))
theano.compile.function_module.UnusedInputError: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 0 is not part of the computational graph needed to compute the outputs: apply_dropout.
To make this error into a warning, you can pass the parameter on_unused_input='warn' to theano.function. To disable it completely, use on_unused_input='ignore'.

Can you help me?

**Comment by iamsile** [comment]
solve it
